#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
COMPOSE_FILE="$REPO_ROOT/docker-compose.yml"
ENV_FILE="${OPENCLAW_ENV_FILE:-$REPO_ROOT/scripts/test-claw.env}"

compose() {
  if ! docker compose version >/dev/null 2>&1; then
    echo "Docker Compose v2 is required. Install the 'docker compose' plugin first." >&2
    exit 1
  fi

  docker compose -f "$COMPOSE_FILE" "$@"
}

generate_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
    return
  fi

  tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64
}

create_env_file() {
  local jwt_secret
  local mqtt_password
  local database_password

  jwt_secret="$(generate_secret)"
  mqtt_password="$(generate_secret)"
  database_password="$(generate_secret)"

  cat >"$ENV_FILE" <<EOF
# Auto-generated by scripts/docker-up.sh
# Public domain
DOMAIN=test-claw.changer.site
PUBLIC_SCHEME=http

# Docker project
COMPOSE_PROJECT_NAME=openclaw-bot-chat

# Reverse proxy / published ports
FRONTEND_PORT_MAPPING=127.0.0.1:4173:3000
BACKEND_PORT_MAPPING=127.0.0.1:8080:8080
POSTGRES_PORT_MAPPING=127.0.0.1:5432:5432
REDIS_PORT_MAPPING=127.0.0.1:6379:6379

# Backend runtime
APP_MODE=release
LOG_LEVEL=info
DATABASE_USER=postgres
DATABASE_PASSWORD=$database_password
DATABASE_DBNAME=openclaw_bot_chat
MQTT_USERNAME=openclaw_backend
MQTT_PASSWORD=$mqtt_password
JWT_SECRET=$jwt_secret
EOF

  echo "Created $ENV_FILE"
}

load_env_file() {
  if [[ ! -f "$ENV_FILE" ]]; then
    create_env_file
  fi

  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a

  : "${DOMAIN:=test-claw.changer.site}"
  : "${PUBLIC_SCHEME:=http}"
  : "${NEXT_PUBLIC_API_URL:=${PUBLIC_SCHEME}://${DOMAIN}}"
  : "${NEXT_PUBLIC_API_WS_HOST:=${DOMAIN}}"

  export NEXT_PUBLIC_API_URL
  export NEXT_PUBLIC_API_WS_HOST
}

parse_frontend_mapping() {
  local mapping

  mapping="${FRONTEND_PORT_MAPPING:-127.0.0.1:4173:3000}"
  IFS=":" read -r part1 part2 part3 <<<"$mapping"

  if [[ -n "${part3:-}" ]]; then
    FRONTEND_BIND_HOST="$part1"
    FRONTEND_BIND_PORT="$part2"
    FRONTEND_CONTAINER_PORT="$part3"
  else
    FRONTEND_BIND_HOST="127.0.0.1"
    FRONTEND_BIND_PORT="$part1"
    FRONTEND_CONTAINER_PORT="$part2"
  fi

  export FRONTEND_BIND_HOST
  export FRONTEND_BIND_PORT
  export FRONTEND_CONTAINER_PORT
}

print_runtime_summary() {
  parse_frontend_mapping

  cat <<EOF
Domain:              ${DOMAIN}
Frontend upstream:   ${FRONTEND_BIND_HOST}:${FRONTEND_BIND_PORT}
Backend upstream:    127.0.0.1:8080
Public URL:          ${PUBLIC_SCHEME}://${DOMAIN}
Env file:            ${ENV_FILE}
EOF
}
