#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
COMPOSE_FILE="$REPO_ROOT/docker-compose.yml"
ENV_FILE="${OPENCLAW_ENV_FILE:-$REPO_ROOT/scripts/test-claw.env}"

compose() {
  if ! docker compose version >/dev/null 2>&1; then
    echo "Docker Compose v2 is required. Install the 'docker compose' plugin first." >&2
    exit 1
  fi

  docker compose -f "$COMPOSE_FILE" "$@"
}

generate_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
    return
  fi

  tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64
}

create_env_file() {
  local jwt_secret
  local mqtt_password
  local database_password

  jwt_secret="$(generate_secret)"
  mqtt_password="$(generate_secret)"
  database_password="$(generate_secret)"

  cat >"$ENV_FILE" <<EOF
# Auto-generated by scripts/docker-up.sh
# Public domain
DOMAIN=test.iotdevices.site
PUBLIC_SCHEME=https
NEXT_PUBLIC_API_URL=\${PUBLIC_SCHEME}://\${DOMAIN}

# Docker project
COMPOSE_PROJECT_NAME=openclaw-bot-chat

# Reverse proxy / published ports
FRONTEND_PORT_MAPPING=127.0.0.1:4173:3000
BACKEND_PORT_MAPPING=127.0.0.1:8080:8080
REDIS_PORT_MAPPING=127.0.0.1:6379:6379
MQTT_TCP_PORT_MAPPING=127.0.0.1:1883:1883
MQTT_WS_PORT_MAPPING=127.0.0.1:8083:8083
EMQX_DASHBOARD_PORT_MAPPING=127.0.0.1:18083:18083

# Backend runtime
APP_MODE=release
LOG_LEVEL=info
DATABASE_USER=postgres
DATABASE_PASSWORD=$database_password
DATABASE_DBNAME=openclaw_bot_chat
MQTT_USERNAME=openclaw_backend
MQTT_PASSWORD=$mqtt_password
MQTT_TCP_PUBLIC_URL=mqtt://127.0.0.1:1883
MQTT_WS_PUBLIC_URL=\${PUBLIC_SCHEME}://\${DOMAIN}/mqtt
JWT_SECRET=$jwt_secret
STORAGE_PROVIDER=
STORAGE_BUCKET=
STORAGE_REGION=
STORAGE_ENDPOINT=
STORAGE_PUBLIC_BASE_URL=
STORAGE_PRIVATE_READ=true
STORAGE_UPLOAD_URL_TTL=900
STORAGE_DOWNLOAD_URL_TTL=900
STORAGE_KEY_PREFIX=chat-assets
STORAGE_COS_SECRET_ID=
STORAGE_COS_SECRET_KEY=
STORAGE_COS_SESSION_TOKEN=
STORAGE_OSS_ACCESS_KEY_ID=
STORAGE_OSS_ACCESS_KEY_SECRET=
STORAGE_OSS_SECURITY_TOKEN=
EOF

  echo "Created $ENV_FILE"
}

load_env_file() {
  if [[ ! -f "$ENV_FILE" ]]; then
    create_env_file
  fi

  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a

  # Prevent unrelated shell exports from forcing object storage on when the
  # selected env file does not configure it.
  if ! grep -Eq '^STORAGE_PROVIDER=' "$ENV_FILE"; then
    STORAGE_PROVIDER=""
  fi
  if ! grep -Eq '^STORAGE_BUCKET=' "$ENV_FILE"; then
    STORAGE_BUCKET=""
  fi
  if ! grep -Eq '^STORAGE_REGION=' "$ENV_FILE"; then
    STORAGE_REGION=""
  fi
  if ! grep -Eq '^STORAGE_ENDPOINT=' "$ENV_FILE"; then
    STORAGE_ENDPOINT=""
  fi
  if ! grep -Eq '^STORAGE_PUBLIC_BASE_URL=' "$ENV_FILE"; then
    STORAGE_PUBLIC_BASE_URL=""
  fi
  if ! grep -Eq '^STORAGE_PRIVATE_READ=' "$ENV_FILE"; then
    STORAGE_PRIVATE_READ="true"
  fi
  if ! grep -Eq '^STORAGE_UPLOAD_URL_TTL=' "$ENV_FILE"; then
    STORAGE_UPLOAD_URL_TTL="900"
  fi
  if ! grep -Eq '^STORAGE_DOWNLOAD_URL_TTL=' "$ENV_FILE"; then
    STORAGE_DOWNLOAD_URL_TTL="900"
  fi
  if ! grep -Eq '^STORAGE_KEY_PREFIX=' "$ENV_FILE"; then
    STORAGE_KEY_PREFIX="chat-assets"
  fi
  if ! grep -Eq '^STORAGE_COS_SECRET_ID=' "$ENV_FILE"; then
    STORAGE_COS_SECRET_ID=""
  fi
  if ! grep -Eq '^STORAGE_COS_SECRET_KEY=' "$ENV_FILE"; then
    STORAGE_COS_SECRET_KEY=""
  fi
  if ! grep -Eq '^STORAGE_COS_SESSION_TOKEN=' "$ENV_FILE"; then
    STORAGE_COS_SESSION_TOKEN=""
  fi
  if ! grep -Eq '^STORAGE_OSS_ACCESS_KEY_ID=' "$ENV_FILE"; then
    STORAGE_OSS_ACCESS_KEY_ID=""
  fi
  if ! grep -Eq '^STORAGE_OSS_ACCESS_KEY_SECRET=' "$ENV_FILE"; then
    STORAGE_OSS_ACCESS_KEY_SECRET=""
  fi
  if ! grep -Eq '^STORAGE_OSS_SECURITY_TOKEN=' "$ENV_FILE"; then
    STORAGE_OSS_SECURITY_TOKEN=""
  fi

  : "${DOMAIN:=test.iotdevices.site}"
  : "${PUBLIC_SCHEME:=https}"
  : "${NEXT_PUBLIC_API_URL:=${PUBLIC_SCHEME}://${DOMAIN}}"
  : "${MQTT_TCP_PUBLIC_URL:=mqtt://127.0.0.1:1883}"
  if [[ -z "${MQTT_WS_PUBLIC_URL:-}" ]]; then
    local ws_scheme
    if [[ "$PUBLIC_SCHEME" == "https" ]]; then
      ws_scheme="wss"
    else
      ws_scheme="ws"
    fi
    MQTT_WS_PUBLIC_URL="${ws_scheme}://${DOMAIN}/mqtt"
  fi

  export NEXT_PUBLIC_API_URL
  export MQTT_TCP_PUBLIC_URL
  export MQTT_WS_PUBLIC_URL
  export STORAGE_PROVIDER
  export STORAGE_BUCKET
  export STORAGE_REGION
  export STORAGE_ENDPOINT
  export STORAGE_PUBLIC_BASE_URL
  export STORAGE_PRIVATE_READ
  export STORAGE_UPLOAD_URL_TTL
  export STORAGE_DOWNLOAD_URL_TTL
  export STORAGE_KEY_PREFIX
  export STORAGE_COS_SECRET_ID
  export STORAGE_COS_SECRET_KEY
  export STORAGE_COS_SESSION_TOKEN
  export STORAGE_OSS_ACCESS_KEY_ID
  export STORAGE_OSS_ACCESS_KEY_SECRET
  export STORAGE_OSS_SECURITY_TOKEN
}

parse_frontend_mapping() {
  local mapping

  mapping="${FRONTEND_PORT_MAPPING:-127.0.0.1:4173:3000}"
  IFS=":" read -r part1 part2 part3 <<<"$mapping"

  if [[ -n "${part3:-}" ]]; then
    FRONTEND_BIND_HOST="$part1"
    FRONTEND_BIND_PORT="$part2"
    FRONTEND_CONTAINER_PORT="$part3"
  else
    FRONTEND_BIND_HOST="127.0.0.1"
    FRONTEND_BIND_PORT="$part1"
    FRONTEND_CONTAINER_PORT="$part2"
  fi

  export FRONTEND_BIND_HOST
  export FRONTEND_BIND_PORT
  export FRONTEND_CONTAINER_PORT
}

parse_backend_mapping() {
  local mapping

  mapping="${BACKEND_PORT_MAPPING:-127.0.0.1:8080:8080}"
  IFS=":" read -r part1 part2 part3 <<<"$mapping"

  if [[ -n "${part3:-}" ]]; then
    BACKEND_BIND_HOST="$part1"
    BACKEND_BIND_PORT="$part2"
    BACKEND_CONTAINER_PORT="$part3"
  else
    BACKEND_BIND_HOST="127.0.0.1"
    BACKEND_BIND_PORT="$part1"
    BACKEND_CONTAINER_PORT="$part2"
  fi

  export BACKEND_BIND_HOST
  export BACKEND_BIND_PORT
  export BACKEND_CONTAINER_PORT
}

print_runtime_summary() {
  parse_frontend_mapping
  parse_backend_mapping

  cat <<EOF
Domain:              ${DOMAIN}
Frontend upstream:   ${FRONTEND_BIND_HOST}:${FRONTEND_BIND_PORT}
Backend upstream:    ${BACKEND_BIND_HOST}:${BACKEND_BIND_PORT}
Public URL:          ${PUBLIC_SCHEME}://${DOMAIN}
Env file:            ${ENV_FILE}
EOF
}
